### ISSUE TITLE
jquery problem

### ISSUE THREAD

**Issue by fuiyu** [totaljs/jRouting#1]
that come a issue when i test the example
 `if (!window.jRoute)
    window.jRoute = [];

window.jRoute.push(function() {
    jRouting.route('/', function() {
        console.log('Classic route');
    });        
    jRouting.route('#hashtag', function() {
        console.log('Hashtag');
    });
});`

**error**:Uncaught TypeError: o.routes.remove is not a function

**Comment by petersirka** [comment]
Hi @fuiyu, I have fixed it. Please download latest version from GitHub.
Thank you!

**Comment by fuiyu** [comment]
thanks a lot! @petersirka
